# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as reg
from loginadmin import Ui_Form1

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(719, 507)
        self.lb10 = QtWidgets.QLabel(Form)
        self.lb10.setGeometry(QtCore.QRect(310, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lb10.setFont(font)
        self.lb10.setObjectName("lb10")
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setGeometry(QtCore.QRect(70, 170, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb1.setFont(font)
        self.lb1.setObjectName("lb1")
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setGeometry(QtCore.QRect(70, 250, 121, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb2.setFont(font)
        self.lb2.setObjectName("lb2")
        self.lb3 = QtWidgets.QLabel(Form)
        self.lb3.setGeometry(QtCore.QRect(70, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb3.setFont(font)
        self.lb3.setObjectName("lb3")
        self.pb2 = QtWidgets.QPushButton(Form)
        self.pb2.setGeometry(QtCore.QRect(330, 300, 81, 31))
        self.pb2.setStyleSheet("color: red;")
        self.pb2.setObjectName("pb2")
        self.tb3 = QtWidgets.QLineEdit(Form)
        self.tb3.setGeometry(QtCore.QRect(220, 200, 351, 21))
        self.tb3.setObjectName("tb3")
        self.tb1 = QtWidgets.QLineEdit(Form)
        self.tb1.setGeometry(QtCore.QRect(220, 160, 351, 21))
        self.tb1.setObjectName("tb1")
        self.tb2 = QtWidgets.QLineEdit(Form)
        self.tb2.setGeometry(QtCore.QRect(220, 240, 351, 21))
        self.tb2.setObjectName("tb2")
        self.pb2.clicked.connect(self.register)
        self.pb2.clicked.connect(self.value)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def value(self):
        self.new=QtWidgets.QMainWindow()
        self.ui=Ui_Form1()
        self.ui.setupUi(self.new)
        self.new.show()
        
    def register(self):

        try:
                db=reg.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="register"    
                )
                mycursor=db.cursor()   
                name=self.tb1.text()
                password=self.tb2.text()
                Email=self.tb3.text()

                query="INSERT INTO admin (name,password,Email) VALUES (%s,%s,%s)"
                value=(name,password,Email)
                mycursor.execute(query,value)
                db.commit()
                # self.label_4.setText("Data inserted")       
        except reg.Error as e:
                print("Error")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb10.setText(_translate("Form", "Register"))
        self.lb1.setText(_translate("Form", "Name "))
        self.lb2.setText(_translate("Form", "Password"))
        self.lb3.setText(_translate("Form", "Email Id"))
        self.pb2.setText(_translate("Form", "Submit"))

if __name__ == "__main__":
        import sys
        app=QtWidgets.QApplication(sys.argv)
        Form=QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())